environment:
  nodejs_version: "10"
cache:
  - '%LOCALAPPDATA%\Yarn -> appveyor.yml'
  - node_modules -> yarn.lock

install:
  - ps: Install-Product node $env:nodejs_version x64
  - yarn
test_script:
  - .\bin\run --help
  - yarn test
after_test:
  - .\node_modules\.bin\nyc report --reporter text-lcov > coverage.lcov

build: off
